# Generated by Django 4.2.2 on 2023-12-02 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Default', max_length=50)),
                ('avatar', models.ImageField(null=True, upload_to=home_app.models.process_upload_user_avatar)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SettingsUser',
        ),
    ]
