# Generated by Django 4.2.2 on 2023-12-06 13:34

from django.db import migrations, models
import home_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_usersettings_delete_settingsuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='avatar',
            field=models.ImageField(default='default-user-icon.jpg', upload_to=home_app.models.process_upload_user_avatar),
        ),
    ]
