# Generated by Django 5.0 on 2024-03-06 13:50

import django.core.validators
import django.db.models.deletion
import forum_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('question', models.TextField(max_length=2048, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('upload', models.ImageField(null=True, upload_to=forum_app.models.process_topic_upload)),
                ('section', models.CharField(choices=[('general', 'Общий'), ('templates', 'Шаблоны'), ('orm', 'Django ORM'), ('testing', 'Тестирование'), ('drf', 'DRF'), ('celery', 'Celery'), ('channels', 'Django Channels'), ('deploy', 'Deploy')], default='general', max_length=10)),
                ('views', models.PositiveIntegerField(default=0)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-time_added',),
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2048, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('upload', models.ImageField(null=True, upload_to=forum_app.models.process_comment_upload)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_app.topic')),
            ],
            options={
                'ordering': ('time_added',),
            },
        ),
    ]
