# Generated by Django 4.2.2 on 2023-12-02 18:56

import django.core.validators
from django.db import migrations, models
import forum_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='upload',
            field=models.ImageField(null=True, upload_to=forum_app.models.process_comment_upload),
        ),
        migrations.AddField(
            model_name='topic',
            name='upload',
            field=models.ImageField(null=True, upload_to=forum_app.models.process_topic_upload),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=2048, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='question',
            field=models.TextField(max_length=2048, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
