# Generated by Django 4.2.2 on 2023-12-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0005_topic_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='header',
            field=models.CharField(choices=[('general', 'Общий'), ('templates', 'Шаблоны'), ('orm', 'Django ORM'), ('testing', 'Тестирование'), ('drf', 'DRF'), ('celery', 'Celery'), ('channels', 'Django Channels'), ('deploy', 'Deploy')], default='general', max_length=30),
        ),
    ]
