# Generated by Django 4.2.2 on 2023-12-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0007_alter_comments_comment_alter_topic_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='header',
            new_name='section',
        ),
    ]
