# Generated by Django 5.0 on 2024-01-18 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0009_alter_comments_comment_alter_topic_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=2048, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='question',
            field=models.TextField(max_length=2048, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='section',
            field=models.CharField(choices=[('general', 'Общий'), ('templates', 'Шаблоны'), ('orm', 'Django ORM'), ('testing', 'Тестирование'), ('drf', 'DRF'), ('celery', 'Celery'), ('channels', 'Django Channels'), ('deploy', 'Deploy')], default='general', max_length=10),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
